# Project Information
site_name: FAIRSACPE GUI Client
site_description: A utility for packaging objects and metadata for FAIRSCAPE.
site_url: https://github.com/fairscape/fairscape-gui

# Repository
repo_name: fairscape/fairscape-gui
repo_url: https://github.com/fairscape/fairscape_gui_client

# Copyright
copyright: Copyright &copy; 2024 THE RECTOR AND VISITORS OF THE UNIVERSITY OF VIRGINIA

# Theme Configuration
theme:
  name: readthedocs
  navigation_depth: 4

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true

# Navigation Structure
nav:
  - Home: index.md
  - Setup: setup.md
  - GUI Instructions: instructions.md

plugins:
  - search:
      lang: en
